# install instable in the jump host
---
- name: Install jenkins
  hosts: jenkins
  gather_facts: false
  become: true
  vars:
    required_packages:
      - fontconfig
      - openjdk-21-jre

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Set hostname
      ansible.builtin.hostname:
        name: jenkins

    - name: Install required_packages (java, fontconfig)
      ansible.builtin.apt:
        name: "{{ required_packages }}"
        state: present

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Jenkins GPG key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
        dest: /etc/apt/keyrings/jenkins-keyring.asc
        mode: "0644"

    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Update apt cache after adding Jenkins repo
      ansible.builtin.apt:
        update_cache: true

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Enable and start Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: true

    - name: Read Jenkins initial admin password (remote file)
      ansible.builtin.slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_pw

    - name: Print Jenkins initial admin password
      ansible.builtin.debug:
        msg: "Jenkins initial admin password: {{ jenkins_pw.content | b64decode }}"
